# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170112_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='url',
            field=models.CharField(max_length=120, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
